### ISSUE TITLE
create list view for citations

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_editor_js#13]
The goal here is to build a page to list citations for each fields in an entity. 

For [example](https://api.popit.sinarproject.org/en/memberships/fbaf165b9a674799b40ec6fce39676a7/citations/)
```
{
    "result": {
        "area_id": [],
        "end_date": [
            {
                "id": "46993d256ed4407e9385a408b3f376a8",
                "label": null,
                "field": "end_date",
                "url": "https://www.linkedin.com/in/shahrol-halmi-82942479",
                "created_at": "2016-07-24T05:43:09.584174Z",
                "updated_at": "2016-07-24T05:43:09.584210Z",
                "note": "Personal LinkedIn Profile page retrieved July 24, 2016",
                "language_code": "en"
            }
        ],
        "on_behalf_of_id": [],
        "created_at": [],
        "language_code": [],
        "updated_at": [],
        "label": [],
        "organization_id": [],
        "post_id": [],
        "master": [],
        "member_id": [],
        "person_id": [],
        "role": [],
        "start_date": [
            {
                "id": "a2bb7a04f39f43aca2006dfe8ea7ce5b",
                "label": null,
                "field": "start_date",
                "url": "https://www.linkedin.com/in/shahrol-halmi-82942479",
                "created_at": "2016-07-24T05:42:57.477646Z",
                "updated_at": "2016-07-24T05:42:57.477693Z",
                "note": "Personal LinkedIn Profile page retrieved July 24, 2016",
                "language_code": "en"
            }
        ]
    }
}
```

Each field in membership have their citation listed in the API access point. The page should list only citations for one [field](https://api.popit.sinarproject.org/en/memberships/fbaf165b9a674799b40ec6fce39676a7/citations/end_date). 

The page should render like src/components/SubItemEntityList.vue. But need to make it work for the URL `/:entity/:entity_id/citations/:field/`

**Comment by Jeffrey04** [comment]
So are you basically looking for to show a given list of citations, possibly in the form of a table? Presumably in the following form?

| area_id | end_date | on_behalf_of_id | created_at | language_code | updated_at | label | organization_id | post_id | master | member_id | person_id | role | start_date |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [] | $something | [] | [] | [] | [] | [] | [] | [] | [] | [] | [] | [] | $something |

However why is every field returning a list, what do I do with them? Also why is there a URL in `start_date` or `end_date`, so what do I display for those fields?

I suppose I can more or less refer to `src/components/SubItemEntityList.vue` for this?

**Comment by sweemeng** [comment]
Each item in a list is a list with the field field populated (example)[https://api.popit.sinarproject.org/en/memberships/fbaf165b9a674799b40ec6fce39676a7/citations/end_date/46993d256ed4407e9385a408b3f376a8]

you can edit it. You can refer to `src/components/SubItemEntityList.vue` but some modification is needed

**Comment by sweemeng** [comment]
implemented
